version: '3'
services:
  lightweight-issuer:
    #image: hub.opensciencegrid.org/sciauth/lightweight-token-issuer
    build: docker-scitokens-java
    volumes:
      - ./user-config.json:/opt/scitokens-server/var/qdl/user-config.txt
      #- /etc/letsencrypt/live/hcc-anvil-175-26.unl.edu/cert.pem:/opt/tomcat/conf/hostcert.pem
      #- /etc/letsencrypt/live/hcc-anvil-175-26.unl.edu/fullchain.pem:/opt/tomcat/conf/hostcert.pem
      #- /etc/letsencrypt/live/hcc-anvil-175-26.unl.edu/privkey.pem:/opt/tomcat/conf/hostkey.pem
      - ./keys.jwk:/opt/scitokens-server/etc/keys.jwk
      - ./file_store:/opt/scitokens-server/var/storage/file_store

    environment:
      - HOSTNAME=<hostname>


    ports:
      - "443:8443"
      - "80:8080"


